repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.6.0
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.19.1"
    hooks:
      - id: blacken-docs
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.15.0
    hooks:
      - id: reorder-python-imports
        args: ["--py39-plus"]
        exclude: "^tests/"
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.5
    hooks:
      - id: poetry-lock
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-type-checking
          - flake8-pyproject
          - flake8-tidy-imports
        args: ["--max-line-length=88"]
        language_version: python3.9
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: ["--py39-plus"]
